import {createCity,analyzeFlood,recoveryState,progress,damageFraction,DAMAGE_CURVE,ASSUMPTIONS,FT,floodHydrograph} from './road-model.js';
import {crewAssignments,EVACUATION_MS} from './road-life.js';
import {RoadScene} from './road-scene.js';
import {RoadGuide} from './road-guide.js';
const cash=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n),length=n=>n>=1000?(n/1000).toFixed(2)+' km':Math.round(n)+' m',days=n=>n.toFixed(1),pct=n=>(100*n).toFixed(1)+'%';
const sourceHTML=`<div class="dialog-header"><span class="eyebrow">THE SCIENCE & THE ASSUMPTIONS</span><button data-road-close aria-label="Close road model notes">×</button></div>
<h2>A defensible teaching model.<br>Not a site forecast.</h2>
<p>Water depth alone cannot determine real road damage or repair time. This lab holds the flood type, road construction and work rates fixed so you can explore one cause at a time.</p>
<h3>1 / Where does the water go?</h3><p>The invented town is a 650 × 450 m grid of 10 m cells. Both streams start at bankfull, the shared zero level. A cell floods only when the water can reach it from a stream across terrain below that level. An isolated low spot stays dry until its lowest connecting barrier is overtopped. Water depth on a road is water level minus its road-surface elevation.</p><p>This is a connected, static level model, not a flow solver. There is no velocity, rainfall, drainage pipe network, water-volume balance or prediction of flood travel time. Recession follows the same level rule, so trapped ponding is not retained. Heights are drawn 8× taller to make terrain easier to read.</p>
<h3>2 / What does a red road mean?</h3><p>Red marks an inundated piece needing assumed cleanup or repair. It does not mean the pavement has collapsed. A 24-hour, slow-moving flood is assumed for every run; the three-second animation is only a visual clock. Local inundation duration is not used to change the damage curve.</p><p>Each 10 × 10 m road piece has an assumed replacement value of $25,000 ($250/m²). Its cost is that value multiplied by the damage fraction at its peak local depth. We sum pieces once; dry portions add zero cost. Buildings, travel delays, business losses, bridge structures, culvert failures, scour and washouts are excluded. The high bridge decks remain above the selectable floods.</p>
<table><caption>Illustrative low-flow damage curve — original teaching values</caption><thead><tr><th>Depth over road (m)</th><th>Fraction of replacement value</th></tr></thead><tbody>${DAMAGE_CURVE.map(([d,f])=>`<tr><td>${d.toFixed(1)}</td><td>${pct(f)}</td></tr>`).join('')}</tbody></table>
<p>The curve uses straight lines between these points. Its shape follows the cleanup/minor-repair interpretation of low-flow road flooding in <a href="https://nhess.copernicus.org/articles/21/1011/2021/" target="_blank" rel="noopener">van Ginkel et al. (2021)</a>; these numbers are not a digitization or calibration of their curves. Pavement research also shows that duration and materials matter: <a href="https://www.sciencedirect.com/science/article/abs/pii/S0950061823021244" target="_blank" rel="noopener">the 2023 pavement flooding study</a>.</p>
<h3>People and crew animations</h3><p>The little residents are story characters, not an evacuation model. A visual thunderstorm sends them to refuges above the chosen peak before water rises. Rain gradually clears by peak water. As repairs finish, residents walk on connected dry or repaired streets; unfinished road pieces stay off limits. Weather and walking animations do not change the flood or damage calculations. Trucks and workers illustrate the scheduled crew jobs; their travel and tool motions do not add cost or time to the model. Peak-water inspection hides crews and places residents back at their dry refuges.</p><h3>3 / How are repair days calculated?</h3><p>We estimate work quantities, then schedule the crews. This follows the production-rate approach described in <a href="https://www.fhwa.dot.gov/construction/contracts/t508015.cfm" target="_blank" rel="noopener">FHWA’s contract-time guidance</a>. All dollar amounts, crew rates and waiting times below are teaching assumptions, not field measurements.</p>
<ul><li>One day after drainage for inspection and mobilization.</li><li>Cleanup: ${ASSUMPTIONS.cleanRate.toLocaleString()} m² per crew-day. Up to $${ASSUMPTIONS.cleanup}/m² of the damage bill is allocated to cleanup.</li><li>Remaining damage dollars ÷ $${ASSUMPTIONS.patch}/m² gives an equivalent surface-repair area; work rate is ${ASSUMPTIONS.patchRate} m² per crew-day.</li><li>A crew-day is one 8-hour shift. We assume a shift every calendar day, supplies on hand and access to every work site. Minimum job duration: one hour.</li><li>Work is grouped into short street sections. Largest jobs are assigned first to the next free crew. Each affected piece is marked restored when its section’s job finishes.</li></ul>
<p><strong>Work days per section = wet area ÷ cleanup rate + equivalent repair area ÷ repair rate.</strong> Start day also includes the crew queue. The shaded range in the recovery chart reruns the schedule with work rates doubled and halved. It is a sensitivity range, not a statistical confidence interval. “Restored” describes completion of modeled work, not certification that a real road is safe to drive.</p>
<p>Severe erosion has a different timescale: <a href="https://www.ncdot.gov/news/press-releases/Pages/2025/2025-09-26-helene-ncdot-one-year-milestone.aspx" target="_blank" rel="noopener">NCDOT documents months of closure and longer permanent reconstruction after Helene</a>. Those high-energy failures are outside this experiment.</p>`;

export class RoadLab{
 constructor(host){
  this.host=host;this.city=createCity();this.event=null;this.day=0;this.peak=4;this.crews=2;this.running=false;this.playing=false;this.expanded=false;this.native=false;this.selected=null;this.spot=null;
  host.innerHTML=`<div class="road-workspace" id="road-workspace">
   <section class="road-stage" aria-label="Choose the flood"><div><span class="eyebrow">01 / SET THE FLOOD</span><label for="road-peak">Peak above stream banks</label></div><div class="road-stage-input"><div class="road-stage-readout"><strong id="road-peak-label">4 ft</strong><span>Bankfull = 0 ft</span></div><input id="road-peak" type="range" min="1" max="8" step="1" value="4" aria-label="Peak water rise above stream banks in feet"><div class="road-ticks">${Array.from({length:8},(_,i)=>`<button data-peak="${i+1}" aria-label="Choose ${i+1} foot flood">${i+1}</button>`).join('')}</div></div><button id="road-run" class="primary-button">Start a 4 ft flood ↗</button></section>
   <div class="road-map-shell"><div class="road-map-tools"><div><b>RIVERBEND</b><span id="road-city-size"></span></div><div><button id="road-zoom-out" aria-label="Zoom out of town">−</button><button id="road-zoom-in" aria-label="Zoom into town">+</button><button id="road-home">Reset view</button><button id="road-guide-toolbar" aria-haspopup="dialog">Guide ↗</button><button id="road-info-toggle" aria-label="Open road information" aria-expanded="false">Info</button><button id="road-expand" aria-label="Expand road experiment">⛶</button></div></div><div id="road-map"><div class="road-map-hud"><span id="road-phase">STREAMS AT BANKFULL</span><strong id="road-water">0.0 <small>ft</small></strong><span>above the banks</span></div><div class="road-life-hud" id="road-life-hud"><span class="road-life-dot"></span><div><strong id="road-life-title">40 residents out & about</strong><span id="road-life-detail">A quiet afternoon in Riverbend</span></div></div><div id="road-loading">Growing a little town…</div><div class="road-map-hint">Drag to pan · Scroll to zoom · Click a road</div><div class="road-compass" aria-hidden="true">N ↑</div></div><div class="road-map-legend"><span><i class="legend-water"></i>Water</span><span><i class="legend-work"></i>Cleanup / repair work</span><span><i class="legend-done"></i>Work finished</span><button id="road-watch-crew" disabled>Find a repair crew ↗</button><label><input type="checkbox" id="road-peek" disabled> Show peak water</label></div></div>
   <aside class="road-sidebar"><button id="road-info-close" aria-label="Close road information">Close ×</button><div class="road-bill"><span>DIRECT ROAD REPAIR COST</span><strong id="road-total">$0</strong><p>Event total · stays recorded after repairs</p></div><div class="road-metrics"><div><span>Road length flooded</span><strong id="road-wet">0 m</strong></div><div><span>All work finished</span><strong id="road-end">—</strong></div></div>
   <div class="road-tabs" role="tablist" aria-label="Road information"><button role="tab" id="road-tab-inspect" data-road-tab="inspect" aria-controls="road-panel-inspect" aria-selected="true">Inspect</button><button role="tab" id="road-tab-curves" data-road-tab="curves" aria-controls="road-panel-curves" aria-selected="false" tabindex="-1">Curves</button><button role="tab" id="road-tab-jobs" data-road-tab="jobs" aria-controls="road-panel-jobs" aria-selected="false" tabindex="-1">Repair jobs</button></div>
   <section id="road-panel-inspect" role="tabpanel" aria-labelledby="road-tab-inspect"><label class="road-select-label" for="road-section">Click a road, or choose a section</label><select id="road-section"><option value="">Choose a road section…</option>${this.city.groups.map(g=>`<option value="${g.id}">${g.name}</option>`).join('')}</select><div id="road-inspection"><div class="road-empty"><span>02</span><h2>Every red piece has a story.</h2><p>Run a flood, then select a road to see how its height, water depth and repair work add up.</p></div></div></section>
   <section id="road-panel-curves" role="tabpanel" aria-labelledby="road-tab-curves" hidden><h3>Depth → damage</h3><p>Local water depth over the pavement, not rise above stream banks.</p><svg id="road-damage-chart" role="img" aria-label="Assumed road depth damage curve"></svg><p id="road-curve-note"></p><h3>Work → recovery</h3><p>Share of all road length with no remaining work. Band: faster / slower work rates.</p><svg id="road-recovery-chart" role="img" aria-label="Road work completion over days after drainage"></svg><p id="road-recovery-note">Run a flood to generate a repair schedule.</p></section>
   <section id="road-panel-jobs" role="tabpanel" aria-labelledby="road-tab-jobs" hidden><p>Jobs are sections of street. Only their flooded pieces contribute to the bill.</p><div id="road-jobs"><p class="road-no-jobs">No flood yet. The crews are on standby.</p></div></section>
   <div class="road-model-note"><span>Illustrative estimates · slow-moving, 24-hour flood</span><button id="road-model-open">Model & sources ↗</button></div></aside>
   <section class="road-recovery" aria-label="Explore recovery"><div><span class="eyebrow">03 / AFTER THE WATER DRAINS</span><label for="road-day">Repair timeline <strong id="road-day-label">Day 0</strong></label><p id="road-timeline-note">Run a flood to unlock the repair timeline.</p></div><div class="road-time-input"><input id="road-day" type="range" min="0" max="1" step="0.05" value="0" disabled aria-label="Days after floodwater drains"><div><span>Drainage / day 0</span><span id="road-day-max">Repairs complete</span></div></div><div class="road-recovery-actions"><label for="road-crews">Repair crews<select id="road-crews"><option value="1">1 crew</option><option value="2" selected>2 crews</option><option value="4">4 crews</option></select></label><button id="road-play-repair" class="primary-button" disabled>▶ Play recovery</button><button id="road-reset">Reset town</button></div></section>
   <dialog id="road-confirm" aria-labelledby="road-confirm-title"><div class="dialog-header"><span class="eyebrow">READY FOR THE WHAT-IF?</span><button data-road-close aria-label="Cancel flood">×</button></div><h2 id="road-confirm-title">Run a 4 ft flood?</h2><p id="road-confirm-copy"></p><p class="road-confirm-note">A thunderstorm sends residents hurrying to dry high ground. Rain eases as the water rises, clearing at peak water. The rise and drainage take 3 seconds. This is a new 24-hour flood scenario; the evacuation and animation clocks are illustrative.</p><div class="lesson-actions"><button id="road-confirm-start" class="primary-button">Start flood</button><button data-road-close class="small-button">Keep exploring</button></div></dialog>
   <dialog id="road-model" aria-label="Road model and scientific sources">${sourceHTML}</dialog>
  </div><div class="road-caption"><span>Water finds connected low ground. Damage remembers the peak.</span><span>Buildings are scenery; estimates cover roads only.</span></div><div class="sr-only" id="road-announcement" role="status" aria-live="polite"></div>`;
  this.$=id=>host.querySelector('#'+id);this.$('road-city-size').textContent='650 × 450 m · '+length(this.city.totalLength)+' of roads';
  try{this.scene=new RoadScene(this.$('road-map'),this.city,(id,spot)=>this.select(id,spot));this.$('road-loading').remove();}catch(e){console.error(e);this.$('road-loading').textContent='3D view unavailable. Use the section menu and repair jobs to explore the same model.';}
  this.bind();this.drawCharts();this.updateLife();this.guide=new RoadGuide(this);
 }
 bind(){const $=this.$;
  $('road-peak').addEventListener('input',e=>this.setPeak(+e.target.value));$('road-peak').addEventListener('change',()=>this.prompt());this.host.querySelectorAll('[data-peak]').forEach(b=>b.addEventListener('click',()=>{this.setPeak(+b.dataset.peak);this.prompt();}));$('road-run').onclick=()=>this.prompt();$('road-confirm-start').onclick=()=>{this.$('road-confirm').close();this.startFlood();};
  this.host.querySelectorAll('[data-road-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('road-model-open').onclick=()=>{this.stopRepair();$('road-model').showModal();};
  $('road-info-toggle').onclick=()=>this.info(!this.$('road-workspace').classList.contains('road-info-open'));$('road-info-close').onclick=()=>this.info(false);
  $('road-watch-crew').onclick=()=>this.watchCrew();
  $('road-section').onchange=e=>this.select(e.target.value);$('road-zoom-in').onclick=()=>this.scene?.zoom(1.2);$('road-zoom-out').onclick=()=>this.scene?.zoom(1/1.2);$('road-home').onclick=()=>this.scene?.home();$('road-peek').onchange=()=>{this.setWater($('road-peek').checked?this.event.peakFt*FT:0,$('road-peek').checked?'PEAK WATER / INSPECTION OVERLAY':'WATER DRAINED / WORK REMAINS');this.update();};
  $('road-day').oninput=e=>{this.stopRepair();this.day=+e.target.value;this.update();};$('road-play-repair').onclick=()=>this.playing?this.stopRepair():this.playRepair();$('road-reset').onclick=()=>this.reset();$('road-crews').onchange=e=>{this.crews=+e.target.value;this.stopRepair();if(this.event){this.prepareEvent(this.event.peakFt);this.day=0;this.update();this.announce('Repair schedule recalculated. The event repair cost is unchanged.');}};
  const tabs=[...this.host.querySelectorAll('[data-road-tab]')];tabs.forEach((b,i)=>{b.onclick=()=>this.panel(b.dataset.roadTab);b.onkeydown=e=>{let j;if(e.key==='ArrowRight')j=(i+1)%tabs.length;if(e.key==='ArrowLeft')j=(i+tabs.length-1)%tabs.length;if(e.key==='Home')j=0;if(e.key==='End')j=tabs.length-1;if(j!==undefined){e.preventDefault();tabs[j].focus();this.panel(tabs[j].dataset.roadTab);}};});
  $('road-expand').onclick=()=>this.expand(!this.expanded);document.addEventListener('fullscreenchange',()=>{if(document.fullscreenElement===$('road-workspace'))this.native=true;else if(this.native){this.native=false;this.applyExpanded(false);}});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&this.expanded&&!this.host.querySelector('dialog[open]')){e.preventDefault();this.expand(false);}});
  new ResizeObserver(()=>this.drawCharts()).observe($('road-sidebar')||this.host.querySelector('.road-sidebar'));
 }
 prepareEvent(peak){this.event=analyzeFlood(this.city,peak,this.crews);this.fast=analyzeFlood(this.city,peak,this.crews,2);this.slow=analyzeFlood(this.city,peak,this.crews,.5);}
 info(on){this.$('road-workspace').classList.toggle('road-info-open',on);this.$('road-info-toggle').setAttribute('aria-expanded',on);if(!on)this.$('road-info-toggle').focus({preventScroll:true});}
 setPeak(n){this.peak=n;this.$('road-peak').value=n;this.$('road-peak-label').textContent=n+' ft';this.$('road-run').textContent='Start '+(n===8?'an ':'a ')+n+' ft flood ↗';}
 prompt(){if(this.running)return;this.$('road-confirm-title').textContent='Run '+(this.peak===8?'an ':'a ')+this.peak+' ft flood?';this.$('road-confirm-copy').textContent='The streams will rise '+this.peak+' ft above their banks. Low roads connected to the streams will flood; higher roads can stay dry. After the water drains, inspect the red pieces and move the repair timeline.';this.$('road-confirm').showModal();}
 lock(active){['road-peak','road-run','road-crews','road-reset'].forEach(id=>this.$(id).disabled=active);this.host.querySelectorAll('[data-peak]').forEach(b=>b.disabled=active);this.$('road-day').disabled=active||!this.event;this.$('road-play-repair').disabled=active||!this.event;this.$('road-peek').disabled=active||!this.event;this.$('road-watch-crew').disabled=active||!this.event?.jobs;this.guide?.refresh();}
 startFlood(){
  this.guide?.dismiss();this.stopRepair();this.day=0;this.running=true;this.$('road-peek').checked=false;this.prepareEvent(this.peak);this.lock(true);this.setWater(0,'THUNDERSTORM / TO HIGH GROUND');this.scene?.paint(null);this.scene?.beginEvacuation(this.peak);this.scene?.setStorm(0);this.update();let start=null,lastPeak=-1;
  const frame=ts=>{
   if(start===null)start=ts;const elapsed=ts-start;this.scene?.setStorm(elapsed);
   if(elapsed<EVACUATION_MS){const safe=this.scene?.evacuate(elapsed/EVACUATION_MS)||0;this.updateLife(safe);this.floodFrame=requestAnimationFrame(frame);return;}
   this.scene?.evacuate(1);this.updateLife(40);const t=elapsed-EVACUATION_MS,h=floodHydrograph(t)*this.peak*FT;
   this.setWater(h,t<1140?'RAIN EASING / WATER RISING':t<1440?'PEAK WATER / SKIES CLEAR':'WATER RECEDING');
   if(h>lastPeak+.015){lastPeak=h;this.scene?.paint(analyzeFlood(this.city,h/FT,this.crews),0);}
   if(t<3000)this.floodFrame=requestAnimationFrame(frame);else this.finishFlood();
  };
  if(matchMedia('(prefers-reduced-motion: reduce)').matches)this.finishFlood();else this.floodFrame=requestAnimationFrame(frame);
 }
 finishFlood(){cancelAnimationFrame(this.floodFrame);this.scene?.clearStorm();this.scene?.evacuate(1);this.running=false;this.setWater(0,'WATER DRAINED / WORK REMAINS');this.lock(false);const worst=[...this.event.groups].sort((a,b)=>b.cost-a.cost)[0];if(worst)this.select(worst.id);this.update();this.announce('Floodwater drained. '+length(this.event.wetLength)+' of roads need work. Estimated repair cost '+cash(this.event.cost)+'. Select a road or explore the repair timeline.');}
 setWater(h,phase){this.scene?.setWater(h);this.$('road-water').innerHTML=(h/FT).toFixed(1)+' <small>ft</small>';this.$('road-phase').textContent=phase;}
 select(id,spot){const g=this.city.groups.find(g=>g.id===id);if(!g)return;this.selected=id;this.spot=spot??[...g.cells].sort((a,b)=>(this.event?.damage.get(b.id).depth||0)-(this.event?.damage.get(a.id).depth||0))[0].id;this.$('road-section').value=id;this.scene?.select(id);this.panel('inspect');if(this.expanded&&matchMedia('(max-width:900px)').matches)this.info(true);this.updateInspector();this.drawCharts();this.guide?.refresh();}
 panel(id){this.host.querySelectorAll('[data-road-tab]').forEach(b=>{const active=b.dataset.roadTab===id;b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1;this.$('road-panel-'+b.dataset.roadTab).hidden=!active;});this.drawCharts();this.guide?.refresh();}
 update(){if(!this.event)return;const e=this.event,s=recoveryState(this.city,e,this.day),$=this.$;
  $('road-total').textContent=cash(e.cost);$('road-wet').textContent=length(e.wetLength);$('road-end').textContent=e.end?'Day '+days(e.end):'No work needed';$('road-day').max=Math.max(1,Math.ceil(e.end));$('road-day').value=this.day;$('road-day-label').textContent='Day '+days(this.day);$('road-day-max').textContent='Day '+Math.ceil(e.end);$('road-timeline-note').textContent=length(s.workLength)+' still awaiting completed work · '+s.complete+' / '+e.jobs+' jobs finished';
  if(!this.running){this.scene?.paint(e,this.day);this.scene?.recovery(e,this.day,$('road-peek').checked);this.updateLife();if(!$('road-peek').checked)$('road-phase').textContent=s.workLength?'WATER DRAINED / WORK REMAINS':e.jobs?'WATER DRAINED / REPAIRS COMPLETE':'WATER DRAINED / NO REPAIRS NEEDED';}this.updateInspector();this.drawCharts();this.drawJobs();this.guide?.refresh();
 }
 updateInspector(){const $=this.$,base=this.city.groups.find(g=>g.id===this.selected);if(!base)return;const g=this.event?.groups.find(g=>g.id===this.selected),cell=this.city.cells[this.spot],hit=this.event?.damage.get(cell.id),p=g?progress(g,this.day):1;const status=!g?'No flood yet':!g.area?'Stayed dry':p>=1?'Work finished':this.day<g.start?'Awaiting crew':'Work in progress';
  $('road-inspection').innerHTML=`<div class="road-selection-head"><span>${status}</span><h2>${base.name}</h2></div><div class="road-spot"><span>SELECTED 10 m ROAD PIECE</span><div><span>Surface above banks</span><strong>${(cell.deck/FT).toFixed(1)} ft</strong></div><div><span>Peak water over this piece</span><strong>${hit?(hit.depth/FT).toFixed(2):'0.00'} ft</strong></div><div><span>Assumed damage fraction</span><strong>${pct(hit?.fraction||0)}</strong></div><div><span>Cost for this piece</span><strong>${cash(hit?.cost||0)}</strong></div><p>$25,000 replacement value × ${pct(hit?.fraction||0)} damage.<br>Cost uses the unrounded fraction.</p></div><div class="road-section-summary"><h3>Whole section / ${length(base.cells.length*10)}</h3><div><span>Flooded portion</span><strong>${length(g?.wetLength||0)}</strong></div><div><span>Section repair bill</span><strong>${cash(g?.cost||0)}</strong></div>${g?.area?`<div><span>Cleanup area</span><strong>${Math.round(g.area)} m²</strong></div><div><span>Equivalent surface repairs</span><strong>${g.patchArea.toFixed(1)} m²</strong></div><div><span>Hands-on work / one crew</span><strong>${days(g.work)} days</strong></div><div><span>Crew ${g.crew} starts → finishes</span><strong>${days(g.start)} → ${days(g.end)} days</strong></div><div class="road-work-meter"><span style="width:${100*p}%"></span></div><p>${Math.round(100*p)}% of scheduled work completed. These days include a shared one-day inspection delay and the crew queue.</p>`:`<p>${this.event?'No cleanup or repair cost is assigned to this section.':'Run a flood to calculate this section’s repair job.'}</p>`}</div>`;
 }
 drawJobs(){const target=this.$('road-jobs');target.replaceChildren();const jobs=this.event.groups.filter(g=>g.area).sort((a,b)=>a.end-b.end);if(!jobs.length){target.innerHTML='<p class="road-no-jobs">No road work is needed for this flood.</p>';return;}for(const g of jobs){const b=document.createElement('button');b.className='road-job';b.innerHTML=`<span>${g.name}<small>${length(g.wetLength)} flooded · Crew ${g.crew}</small></span><span>${cash(g.cost)}<small>${progress(g,this.day)>=1?'Finished':'Finish day '+days(g.end)}</small></span>`;b.onclick=()=>this.select(g.id);target.append(b);}}
 stopRepair(){this.playing=false;cancelAnimationFrame(this.repairFrame);this.$('road-play-repair').textContent='▶ Play recovery';this.$('road-play-repair').setAttribute('aria-pressed','false');}
 playRepair(){if(!this.event||this.running)return;if(this.day>=this.event.end)this.day=0;this.playing=true;this.$('road-play-repair').textContent='Ⅱ Pause recovery';this.$('road-play-repair').setAttribute('aria-pressed','true');let last=null,paint=0;const frame=t=>{if(!this.playing)return;if(last!==null)this.day=Math.min(this.event.end,this.day+(t-last)/1000*Math.max(.15,this.event.end/28));last=t;if(t-paint>90){this.update();paint=t;}if(this.day>=this.event.end){this.stopRepair();this.update();this.announce('All modeled road work is complete. The event repair bill stays recorded.');}else this.repairFrame=requestAnimationFrame(frame);};this.repairFrame=requestAnimationFrame(frame);}
 drawCharts(){const $=this.$,hit=this.event?.damage.get(this.spot),end=this.event?.end||1;this.chart($('road-damage-chart'),8,5,x=>damageFraction(x*FT)*100,{x:'Depth over road (ft)',y:'Repair / replacement (%)',marker:hit?.depth/FT});$('road-curve-note').textContent=hit?'Selected piece: '+(hit.depth/FT).toFixed(2)+' ft → '+pct(hit.fraction)+' of replacement cost.':'Illustrative low-flow curve. Even a wet road may need only cleanup.';
  const e=this.event,max=Math.max(1,Math.ceil(this.slow?.end||2*end));this.chart($('road-recovery-chart'),max,100,x=>e?100*recoveryState(this.city,e,x).restored:100,{x:'Days after drainage',y:'Road length restored (%)',marker:this.day,band:e?[x=>100*this.recoveryAtRate(x,2),x=>100*this.recoveryAtRate(x,.5)]:null});$('road-recovery-note').textContent=e?'Solid line: selected crew plan. All work ends around day '+days(end)+'. Shading changes work rates only.':'Run a flood to generate a repair schedule.';
 }
 recoveryAtRate(day,rate){return recoveryState(this.city,rate===2?this.fast:this.slow,day).restored;}
 chart(svg,xmax,ymax,fn,opts){const w=320,h=180,l=39,r=10,t=27,b=34,pw=w-l-r,ph=h-t-b,x=v=>l+v/xmax*pw,y=v=>t+ph-v/ymax*ph;let html=`<title>${opts.y} versus ${opts.x}</title>`;for(let k=0;k<=4;k++){const val=ymax*k/4;html+=`<path d="M${l} ${y(val)}H${w-r}" stroke="#36515a"/><text x="${l-6}" y="${y(val)+4}" text-anchor="end">${Number(val.toFixed(2))}</text><text x="${x(xmax*k/4)}" y="${h-b+17}" text-anchor="middle">${Number((xmax*k/4).toFixed(1))}</text>`;}const samples=160,points=fn=>Array.from({length:samples+1},(_,i)=>[x(xmax*i/samples),y(fn(xmax*i/samples))]);if(opts.band){const a=points(opts.band[0]),b=points(opts.band[1]).reverse();html+=`<path d="M${[...a,...b].map(p=>p.join(',')).join('L')}Z" fill="#b4f5d0" opacity=".11"/>`;}html+=`<path d="M${points(fn).map(p=>p.join(',')).join('L')}" fill="none" stroke="#b4f5d0" stroke-width="2.4"/>`;if(Number.isFinite(opts.marker)){const m=Math.min(xmax,Math.max(0,opts.marker));html+=`<path d="M${x(m)} ${t}V${h-b}" stroke="#ffe2a1" stroke-dasharray="3 3"/><circle cx="${x(m)}" cy="${y(fn(m))}" r="4" fill="#ffe2a1"/>`;}html+=`<text x="${l}" y="13">${opts.y}</text><text x="${l+pw/2}" y="${h-1}" text-anchor="middle">${opts.x}</text>`;svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.innerHTML=html;}
 reset(){this.guide?.dismiss();cancelAnimationFrame(this.floodFrame);this.running=false;this.stopRepair();this.event=null;this.fast=null;this.slow=null;this.day=0;this.$('road-peek').checked=false;this.scene?.paint(null);this.scene?.resetLife();this.updateLife();this.setWater(0,'STREAMS AT BANKFULL');this.$('road-total').textContent='$0';this.$('road-wet').textContent='0 m';this.$('road-end').textContent='—';this.$('road-day').value=0;this.$('road-day').max=1;this.$('road-day-max').textContent='Repairs complete';this.$('road-day-label').textContent='Day 0';this.$('road-timeline-note').textContent='Run a flood to unlock the repair timeline.';this.$('road-jobs').innerHTML='<p class="road-no-jobs">No flood yet. The crews are on standby.</p>';this.lock(false);this.updateInspector();this.drawCharts();this.announce('Town reset. Streams are back at bankfull.');}
 updateLife(safe){
  const $=this.$,title=$('road-life-title'),detail=$('road-life-detail');
  $('road-life-hud').classList.toggle('evacuating',safe!==undefined&&safe<40);
  if(safe!==undefined){title.textContent=safe<40?'Storm warning! Find high ground.':'Everyone is safe';detail.textContent=safe<40?safe+' / 40 residents at dry refuges':'40 / 40 reached dry refuges';return;}
  if(!this.event){title.textContent='40 residents out & about';detail.textContent='A quiet afternoon in Riverbend';return;}
  const returning=this.scene?.actors.returning||0;title.textContent=returning?'Residents returning to the streets':'All 40 residents are safe';
  const crews=crewAssignments(this.city,this.event,this.day);
  detail.textContent=$('road-peek').checked?'Peak-water overlay · crews hidden':this.day<1?'Inspection first · crews start on day 1':crews.length?crews.length+' crews working'+(returning?' · '+returning+' residents out walking':' · find one below'):this.day>=this.event.end?'Road repairs complete · '+returning+' residents out walking':'Crews ready for their next job';
 }
 watchCrew(){
  if(!this.event||this.running)return;
  this.stopRepair();this.$('road-peek').checked=false;this.setWater(0,'WATER DRAINED / WORK REMAINS');
  const active=crewAssignments(this.city,this.event,this.day),job=active[0]?.job||this.event.groups.filter(g=>g.work).sort((a,b)=>a.start-b.start)[0];
  if(!job)return;this.day=job.start+job.work*.55;this.update();const c=crewAssignments(this.city,this.event,this.day).find(a=>a.job.id===job.id)?.cell||job.cells[0];
  this.select(job.id,c.id);this.scene?.focus(c);this.announce('Watching crew '+job.crew+' on '+job.name+'. The timeline is paused; the workers show this job in progress.');
 }
 announce(text){this.$('road-announcement').textContent=text;}
 applyExpanded(on){this.expanded=on;this.$('road-workspace').classList.toggle('road-expanded',on);document.body.classList.toggle('road-is-expanded',on);this.$('road-expand').textContent=on?'Exit ×':'⛶';this.$('road-expand').setAttribute('aria-label',on?'Exit expanded road experiment':'Expand road experiment');this.$('road-expand').setAttribute('aria-pressed',on);document.querySelectorAll('.topbar,.module-tabs,.road-intro,footer').forEach(el=>el.inert=on);requestAnimationFrame(()=>this.scene?.resize());}
 async expand(on){if(on){this.scroll=window.scrollY;this.applyExpanded(true);try{await this.$('road-workspace').requestFullscreen?.();}catch{}}else{try{if(document.fullscreenElement===this.$('road-workspace'))await document.exitFullscreen();}catch{}this.applyExpanded(false);window.scrollTo(0,this.scroll||0);}}
 show(){requestAnimationFrame(()=>this.scene?.resize());}
 hide(){this.stopRepair();if(this.running)this.finishFlood();this.host.querySelectorAll('dialog[open]').forEach(d=>d.close());if(this.expanded)this.expand(false);}
}
