export const STEPS=[
 {title:'Set the storm.',copy:'Choose how much rain falls and how readily it enters the soil. These are inputs to hydrology.',info:'inputs',next:'2 · Follow the runoff →'},
 {title:'Follow the runoff.',copy:'Some rain enters the soil. The rest flows toward streams. Hydrology turns that runoff into a discharge hydrograph.',info:'processes',next:'3 · See the flooding →'},
 {title:'See the flooding.',copy:'The flow now spreads across the low ground. Hydraulics describes where water goes, how deep it is, and how high its surface rises.',info:'hydraulics',next:'4 · Change & compare →'},
 {title:'Change one thing.',copy:'Increase the rainfall or reduce infiltration. Watch discharge rise and the illustrated flood become wider and deeper.',info:'comparison',next:'Complete experiment ✓'}
];
export const INFO={
 inputs:['What does hydrology need?',`<p><strong>Rainfall</strong> supplies water. The <strong>infiltration setting</strong> controls how readily rain enters the ground. <strong>Land cover</strong> influences interception, evaporation and runoff. <strong>Terrain</strong> directs water toward streams.</p><p>Use the layer buttons on the map to explore these inputs. Rohan Creek is an imaginary basin: all its streams lead to one outlet.</p>`],
 rainfall:['Rainfall is an input, not flood depth.',`<p>A rainfall total of 85 mm means that amount fell over the basin during the storm. It does not mean floodwater is 85 mm deep everywhere.</p><p>Here the rainfall is distributed over six hours unless you change the duration. Shorter storms with the same total can create a sharper flow peak. Cloud cover and falling rain preview the chosen intensity.</p>`],
 infiltration:['What is infiltration?',`<p>Infiltration is water entering soil pores. Soil properties and existing wetness control the available storage and the rate at which water enters.</p><p><strong>Higher infiltration:</strong> more rain enters the soil, leaving less immediate runoff. <strong>Lower infiltration:</strong> more rain stays above ground and reaches streams.</p><p>This control adjusts both available soil storage and infiltration capacity in the teaching model. It is a scenario setting, not a measurement of real soil.</p>`],
 processes:['Follow water through the catchment.',`<p><strong>Interception:</strong> leaves temporarily hold rain. <strong>Infiltration:</strong> water enters soil. <strong>Evapotranspiration:</strong> evaporation and plants return water to the atmosphere.</p><p><strong>Overland flow:</strong> excess water travels downslope into streams. <strong>Stream routing:</strong> travel and temporary storage spread its arrival out in time.</p><p>The enlarged arrows and cutaway are process illustrations. The hydrologic model accounts for water volume and travel time separately.</p>`],
 hydrograph:['Discharge is a rate, not a height.',`<p>The curve shows <strong>discharge Q (m³/s)</strong> over time. A value of 25 m³/s means 25 cubic metres pass a location every second.</p><p>The peak is the largest flow rate; its timing tells us when it occurs. The area under the curve is a volume. None of these alone specifies flood depth at a house.</p><p>In step 4, you can pin several runs and compare them. Restarting clears the saved runs.</p>`],
 hydraulics:['From discharge to inundation.',`<p>A hydraulic model combines incoming flow with <strong>terrain, channel geometry, resistance and boundary conditions</strong> to describe water movement and flood conditions.</p><p>Its outputs include <strong>water depth, water-surface elevation, velocity and inundation extent</strong>. A mesh is a set of connected cells across the terrain.</p><p><strong>This scene is illustrative:</strong> a fixed flow-to-level relation raises and lowers the water surface in response to the hydrograph. Only connected low ground below that surface is shown as flooded. This makes the cause-and-effect visible; it is not a numerical shallow-water solution or a forecast.</p>`],
 outputs:['Four different views of the same flood.',`<p><strong>Depth:</strong> water above the ground, in metres. <strong>Water elevation:</strong> the height of the water surface relative to the scene’s local vertical datum.</p><p><strong>Velocity:</strong> an illustrative speed and direction of movement. <strong>Extent:</strong> the footprint of cells deeper than 0.10 m.</p><p>The terrain and water surface are vertically exaggerated for visibility. Read the labels and legend for values; decorative houses and bridges are not resolved flow obstacles.</p>`],
 depth:['Depth versus water-surface elevation.',`<div class="equation">Water depth = water elevation − ground elevation</div><p>For example, if the ground is at 7 m and the water surface is at 9 m above the same datum, the water is <strong>2 m deep</strong>.</p><p>The fixed village-edge point lets you compare the same location between storms. A dash for elevation means this point is dry. The elevation reference is local to this imaginary world, not sea level.</p>`],
 mesh:['Why a mesh?',`<p>A mesh divides terrain into cells. In a hydraulic simulation, cells store water and exchange it across their shared boundaries. Finer cells can represent smaller features, but require more computation.</p><p>The grid shown here has 50 m cells. The flood illustration identifies connected low cells and clips the visible water surface to the terrain. Decorative buildings do not divert the illustrated water.</p>`],
 comparison:['Make a fair comparison.',`<p>The original storm is saved when you enter step 4. Change <strong>one input at a time</strong>, leaving terrain and the flow-to-level relation unchanged.</p><p>More rainfall or lower infiltration generally produces more event runoff. In this example, greater discharge gives a higher water surface, deeper water in low areas and a larger footprint.</p><p>In reality, backwater, structures, downstream levels and floodplain storage also matter. This controlled illustration isolates the rainfall–runoff connection.</p>`]
};
export {METHODS} from './equations.mjs';
