import * as THREE from 'three';
import {terrain,streams,inside,center,width,landUse,channelDistance,clamp} from './model.mjs';

// Process illustrations have deliberately enlarged symbols, not hydraulic depth.
export class ProcessEffects{
 constructor(world){this.w=world;this.process='none';this.group=new THREE.Group();world.scene.add(this.group);this.group.visible=false;this.seeds=[];
  for(let i=0;i<1500&&this.seeds.length<140;i++){const z=250+world.rand()*3550,x=center(z)+(world.rand()-.5)*width(z)*1.7;if(!inside(x,z)||channelDistance(x,z).d<45||landUse(x,z)===2)continue;let best=Infinity,target;for(const s of streams)for(let j=1;j<s.points.length;j++){const[a,b]=s.points[j-1],[c,d]=s.points[j],dx=c-a,dz=d-b,t=clamp(((x-a)*dx+(z-b)*dz)/(dx*dx+dz*dz),0,1),px=a+t*dx,pz=b+t*dz,dist=Math.hypot(x-px,z-pz);if(dist<best){best=dist;target=[px,pz];}}this.seeds.push({x,z,target,a:world.rand()});}
  this.dummy=new THREE.Object3D();this.axis=new THREE.Vector3(0,1,0);this.direction=new THREE.Vector3();
  const material=new THREE.MeshBasicMaterial({color:'#257bbb',depthTest:false,depthWrite:false,toneMapped:false,transparent:true,opacity:.9});
  this.heads=new THREE.InstancedMesh(new THREE.ConeGeometry(.11,.29,6),material,this.seeds.length);this.shafts=new THREE.InstancedMesh(new THREE.CylinderGeometry(.036,.036,.55,5),material,this.seeds.length);this.heads.frustumCulled=this.shafts.frustumCulled=false;this.heads.renderOrder=this.shafts.renderOrder=7;this.group.add(this.heads,this.shafts);
  const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(new Float32Array(this.seeds.length*16*6),3));this.paths=new THREE.LineSegments(geometry,new THREE.LineBasicMaterial({color:'#f8df95',transparent:true,opacity:.68,depthWrite:false,depthTest:false,toneMapped:false}));this.paths.frustumCulled=false;this.paths.renderOrder=6;this.group.add(this.paths);
 }
 set(process){this.process=process;this.group.visible=['infiltration','evaporation','overland'].includes(process);this.paths.visible=process==='overland';this.heads.material.color.set(process==='evaporation'?'#c38936':process==='overland'?'#087e9e':'#237ac0');if(process==='overland'){const p=this.paths.geometry.attributes.position;let n=0;for(const s of this.seeds)for(let j=0;j<16;j++)for(const t of [j/16,(j+1)/16]){const x=s.x+(s.target[0]-s.x)*t,z=s.z+(s.target[1]-s.z)*t;p.setXYZ(n++,x/50,(terrain(x,z)+1.8)/14,(z-2100)/50);}p.needsUpdate=true;this.paths.geometry.setDrawRange(0,n);}}
 update(time){if(!this.group.visible)return;const scale=clamp(this.w.camera.position.distanceTo(this.w.controls.target)/90,.55,2.5),process=this.process;
  for(let i=0;i<this.seeds.length;i++){const s=this.seeds[i],u=(time/(process==='overland'?7:3.2)+s.a)%1;let x=s.x,z=s.z,y;
   if(process==='overland'){x+=(s.target[0]-x)*u;z+=(s.target[1]-z)*u;y=terrain(x,z)+2;const ahead=Math.min(1,u+.025),px=s.x+(s.target[0]-s.x)*ahead,pz=s.z+(s.target[1]-s.z)*ahead;this.direction.set((px-x)/50,(terrain(px,pz)+2-y)/14,(pz-z)/50).normalize();}
   else{y=terrain(x,z)+3+(process==='infiltration'?1-u:u)*28*scale;this.direction.set(0,process==='infiltration'?-1:1,0);}
   this.dummy.quaternion.setFromUnitVectors(this.axis,this.direction);this.dummy.scale.setScalar(scale);this.dummy.position.set(x/50,y/14,(z-2100)/50);this.dummy.position.addScaledVector(this.direction,.31*scale);this.dummy.updateMatrix();this.heads.setMatrixAt(i,this.dummy.matrix);this.dummy.position.addScaledVector(this.direction,-.40*scale);this.dummy.updateMatrix();this.shafts.setMatrixAt(i,this.dummy.matrix);
  }this.heads.instanceMatrix.needsUpdate=true;this.shafts.instanceMatrix.needsUpdate=true;
 }
}

const sketches={
 rainfall:{title:'Rainfall reaches the surface',look:'Watch the streaks descend from the clouds. More rain in less time produces a more intense storm.',key:'INPUT · WATER FROM THE ATMOSPHERE',art:`<path d="M18 107Q78 85 136 109T294 104V150H18Z" fill="#c4d0a1"/><path d="M69 35q0-18 20-16q12-25 32-8q22-11 32 11q22-3 24 20H69Z" fill="#acbdc5"/>${[81,105,132,157,189,220].map((x,i)=>`<path class="sketch-rain" style="animation-delay:${-i*.3}s" d="M${x} 50l-8 19" stroke="#428da9" stroke-width="3" stroke-linecap="round"/>`).join('')}<text x="207" y="39">clouds</text><text x="206" y="143">land surface</text>`},
 infiltration:{title:'Into the soil',look:'Blue arrows mark water entering the ground. The cutaway shows what the terrain hides: water moving into soil pores.',key:'PROCESS · SURFACE → SOIL',art:`<path d="M18 66H295V151H18Z" fill="#c7ad86"/><path d="M18 66H295V87H18Z" fill="#918263"/><path d="M18 66H295" stroke="#8aaa75" stroke-width="8"/>${[58,117,176].map((x,i)=>`<path class="sketch-infiltrate" style="animation-delay:${-i*.7}s" d="M${x} 36v37m-6-7l6 7 6-7" fill="none" stroke="#247baf" stroke-width="3" stroke-linecap="round"/>`).join('')}<path d="M38 117h146m-115 18h135" stroke="#ead2ad" stroke-width="2" stroke-dasharray="3 13"/><text x="221" y="49">rain</text><text x="215" y="103">soil pores</text><text x="20" y="170">ILLUSTRATED SOIL CUTAWAY</text>`},
 evaporation:{title:'Back to the atmosphere',look:'Gold arrows rise from the land and vegetation. Water evaporates from wet surfaces; plants release water by transpiration.',key:'PROCESS · LAND & PLANTS → AIR',art:`<path d="M18 136H295V153H18Z" fill="#c4d0a1"/><path d="M221 133V88" stroke="#927652" stroke-width="7"/><path d="M195 94q-17-25 6-31q-3-29 23-27q30-3 25 29q30 21 0 33Z" fill="#82a080"/><path d="M29 133q35-12 83 0" stroke="#60a4b1" stroke-width="6"/>${[64,100,216,245].map((x,i)=>`<path class="sketch-evaporate" style="animation-delay:${-i*.6}s" d="M${x} 97v-37m-6 6l6-7 6 7" fill="none" stroke="#b3853d" stroke-width="3" stroke-linecap="round"/>`).join('')}<text x="26" y="24">evaporation</text><text x="177" y="24">transpiration</text>`},
 overland:{title:'Across the land, into a stream',look:'Follow the moving teal arrows along the highlighted surface paths. Excess rainfall joins the nearest tributary.',key:'PROCESS · HILLSLOPE → STREAM',art:`<path d="M18 57Q82 64 145 108T267 129L297 120V153H18Z" fill="#c1cea0"/><path d="M18 55Q82 62 145 106T265 127" fill="none" stroke="#839c6e" stroke-width="5"/><path d="M249 126q22 12 48-7" fill="none" stroke="#4f9daf" stroke-width="9"/><path class="sketch-runoff" d="M30 45Q91 57 149 97T258 116" fill="none" stroke="#1684a4" stroke-width="4" stroke-dasharray="10 13"/><path d="M240 108l17 8-15 7" fill="none" stroke="#1684a4" stroke-width="3"/><text x="27" y="30">excess rainfall</text><text x="232" y="170">stream</text>`},
 routing:{title:'Along streams, toward the outlet',look:'Watch the bright traces move down the tributaries and merge in Rohan Creek. Travel and storage spread the runoff out in time.',key:'PROCESS · TRIBUTARIES → OUTLET',art:`<path d="M45 35Q99 51 143 93M245 27Q213 63 143 93M146 24V93Q117 133 213 143" fill="none" stroke="#8bb5af" stroke-width="14" stroke-linecap="round"/><path class="sketch-runoff" d="M45 35Q99 51 143 93Q117 133 213 143M245 27Q213 63 143 93M146 24V93" fill="none" stroke="#f7f7d7" stroke-width="3" stroke-dasharray="8 11"/><circle cx="215" cy="143" r="9" fill="#d4b570"/><text x="224" y="147">outlet</text>`}
};
export function showProcessLens(host,process){const s=sketches[process];host.hidden=!s;if(!s)return;host.dataset.illustration=process;host.innerHTML=`<div class="process-lens-head"><span>${s.key}</span><button id="close-process" aria-label="Stop process illustration">×</button></div><h3>${s.title}</h3><svg viewBox="0 0 315 180" role="img" aria-label="Animated illustration: ${s.title}">${s.art}</svg><p>${s.look}</p><small>Symbols are enlarged illustrations, not water depths.</small>`;}
