import * as THREE from 'three';
import {streams,terrain,bed,inside,center,width,clamp,NX,NZ,DX,X0,Z0} from './model.mjs';
const position=(x,z,h)=>[x/50,h/14,(z-2100)/50];
export class WaterEffects{
 constructor(w){this.w=w;this.enabled=true;this.cloudsEnabled=true;this.rain=85;this.duration=6;this.pattern='uniform';this.clock=0;
  this.paths=streams.map(s=>{const pts=w.interpolate(s.points,8),d=[0];for(let i=1;i<pts.length;i++)d.push(d.at(-1)+Math.hypot(pts[i][0]-pts[i-1][0],pts[i][1]-pts[i-1][1]));return {pts,d,length:d.at(-1),main:s.main};});
  this.traces=[];for(const p of this.paths)for(let i=0;i<(p.main?76:38);i++)this.traces.push({p,s:w.rand()*p.length,lane:(w.rand()-.5)*(p.main?24:7),rate:.7+w.rand()*.6});
  this.streamLines=this.lines(this.traces.length*3,'#e4f7e4',.75);this.floodLines=this.lines(600*3,'#f5fff2',.95);this.floodTraces=[];this.floodLines.renderOrder=5;
  this.rainSeeds=Array.from({length:3200},()=>{const z=150+w.rand()*3800;return {x:center(z)+(w.rand()-.5)*width(z)*1.85,z,a:w.rand()};});this.rainLines=this.lines(3200,'#b6d0d2',.65);this.rainLines.visible=false;
  const canvas=document.createElement('canvas');canvas.width=canvas.height=128;const ctx=canvas.getContext('2d'),g=ctx.createRadialGradient(64,64,8,64,64,64);g.addColorStop(0,'rgba(255,255,255,.95)');g.addColorStop(.55,'rgba(255,255,255,.65)');g.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=g;ctx.fillRect(0,0,128,128);const texture=new THREE.CanvasTexture(canvas);this.clouds=new THREE.Group();w.scene.add(this.clouds);this.cloudParts=[];
  for(let i=0;i<100;i++){const z=250+w.rand()*3600,x=center(z)+(w.rand()-.5)*width(z)*1.45,cloud=new THREE.Group();cloud.position.set(x/50,(terrain(x,z)+150+w.rand()*30)/14,(z-2100)/50);this.clouds.add(cloud);for(let j=0;j<5;j++){const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,color:'#f4f5e9',transparent:true,opacity:.75,depthWrite:false}));sprite.position.set((w.rand()-.5)*3.5,w.rand()*1.1,(w.rand()-.5)*2);sprite.scale.set(4+w.rand()*3,2.2+w.rand()*1.5,1);cloud.add(sprite);}this.cloudParts.push({cloud,z,x});}
 }
 lines(n,color,opacity){const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(new Float32Array(n*6),3));const l=new THREE.LineSegments(g,new THREE.LineBasicMaterial({color,transparent:true,opacity,depthWrite:false,toneMapped:false}));l.frustumCulled=false;this.w.scene.add(l);return l;}
 at(p,s,lane=0){s=clamp(s,0,p.length-.01);let lo=0,hi=p.d.length-1;while(hi-lo>1){const m=(lo+hi)>>1;if(p.d[m]>s)hi=m;else lo=m;}const t=(s-p.d[lo])/(p.d[hi]-p.d[lo]),a=p.pts[lo],b=p.pts[hi],dx=b[0]-a[0],dz=b[1]-a[1],len=Math.hypot(dx,dz);return [a[0]+dx*t-dz/len*lane,a[1]+dz*t+dx/len*lane];}
 setData(o){this.rain=o.rain??85;this.duration=o.duration??6;this.pattern=o.pattern;}
 setFrame(result,frame,mode){const changed=this.result!==result;this.result=result;this.frame=frame;this.mode=mode;this.wet=[];for(let k=0;k<frame.h.length;k++)if(result.grid.mask[k]&&frame.h[k]>.1&&Math.hypot(frame.ux[k],frame.uz[k])>.015)this.wet.push(k);if(!this.wet.length)this.floodTraces=[];else if(changed||!this.floodTraces.length){this.floodTraces=[];for(let i=0;i<600;i++)this.floodTraces.push(this.seed(i));}}
 seed(i){const k=this.wet[Math.floor(this.w.rand()*this.wet.length)];return {x:X0+(k%NX+.18+this.w.rand()*.64)*DX,z:Z0+(Math.floor(k/NX)+.18+this.w.rand()*.64)*DX,life:i%12};}
 cell(x,z){const i=Math.floor((x-X0)/DX),j=Math.floor((z-Z0)/DX);return i<0||i>=NX||j<0||j>=NZ?-1:j*NX+i;}
 update(seconds,dt){const w=this.w,active=w.phase!=='hydraulics'&&(w.process==='rainfall'||w.layer==='rainfall'),intensity=this.rain/this.duration,strength=clamp(intensity/(160/3),0,1);this.clock+=dt;
  this.clouds.visible=active&&this.cloudsEnabled;this.rainLines.visible=active;
  if(active){const count=Math.round(350+strength*2850),a=this.rainLines.geometry.attributes.position;for(let i=0;i<count;i++){const s=this.rainSeeds[i],u=(seconds*(.65+strength*.9)+s.a)%1,regional=this.pattern==='headwaters'?(s.z<1670?1:.4):1,y=terrain(s.x,s.z)+(1-u)*135;const visible=i<count*regional;for(let j=0;j<2;j++){const p=visible?position(s.x+(1-u)*14,s.z,y+j*(4+strength*10)):[0,-100,0];a.setXYZ(i*2+j,...p);}}a.needsUpdate=true;this.rainLines.geometry.setDrawRange(0,count*2);this.rainLines.material.opacity=.4+strength*.4;this.cloudParts.forEach(({cloud,z},i)=>{cloud.visible=i<(this.pattern==='headwaters'&&z>1670?18:36+strength*64);for(const s of cloud.children){s.material.color.set('#f4f3e7').lerp(new THREE.Color('#718995'),strength*.7);s.material.opacity=.42+strength*.23;}});}
  const numerical=w.phase==='hydraulics'&&w.floodGroup.visible&&this.frame;this.streamLines.visible=this.enabled&&!numerical;this.floodLines.visible=!!(this.enabled&&numerical);
  if(this.streamLines.visible){const a=this.streamLines.geometry.attributes.position;let n=0;for(const tr of this.traces){tr.s=(tr.s+dt*(w.process==='routing'?54:25)*(1+strength)*tr.rate)%tr.p.length;for(let j=0;j<3;j++){const p=this.at(tr.p,tr.s-j*4,tr.lane),q=this.at(tr.p,tr.s-(j+1)*4,tr.lane);a.setXYZ(n++,...position(p[0],p[1],bed(p[1])+.31));a.setXYZ(n++,...position(q[0],q[1],bed(q[1])+.31));}}a.needsUpdate=true;}
  if(this.floodLines.visible){const f=this.frame,a=this.floodLines.geometry.attributes.position;let n=0;for(let i=0;i<this.floodTraces.length;i++){let tr=this.floodTraces[i],k=this.cell(tr.x,tr.z);tr.life+=dt;if(k<0||f.h[k]<=.1||Math.hypot(f.ux[k],f.uz[k])<.015||tr.life>12){tr=this.floodTraces[i]=this.seed(i);k=this.cell(tr.x,tr.z);}const dx=f.ux[k]*dt*80,dz=f.uz[k]*dt*80,nk=this.cell(tr.x+dx,tr.z+dz);if(nk>=0&&f.h[nk]>.1){tr.x+=dx;tr.z+=dz;k=nk;}else tr.life=13;
    const speed=Math.hypot(f.ux[k],f.uz[k])||1;for(let j=0;j<3;j++){const px=tr.x-f.ux[k]/speed*j*5,pz=tr.z-f.uz[k]/speed*j*5,qx=px-f.ux[k]/speed*5,qz=pz-f.uz[k]/speed*5,kp=this.cell(px,pz),kq=this.cell(qx,qz);if(kp<0||kq<0||f.h[kp]<=.1||f.h[kq]<=.1){a.setXYZ(n++,0,-100,0);a.setXYZ(n++,0,-100,0);continue;}a.setXYZ(n++,...position(px,pz,this.result.illustrative?bed(pz)+f.stage+.15:terrain(px,pz)+(this.mode==='extent'?.5:f.h[kp]+.45)));a.setXYZ(n++,...position(qx,qz,this.result.illustrative?bed(qz)+f.stage+.15:terrain(qx,qz)+(this.mode==='extent'?.5:f.h[kq]+.45)));}}
   a.needsUpdate=true;this.floodLines.geometry.setDrawRange(0,n);
  }
 }
}
